"""
AURA — Mock Veri Deposu
========================
Tüm servisler ve route'lar veriyi buradan alır.
Gerçek DB'ye geçince sadece bu dosya değişir, route'lar dokunulmaz.
"""

orders = [
    {
        "id": "A-240501",
        "customer_id": "C-001",
        "customer_name": "Elif Yılmaz",
        "product_id": "PRD-1001",
        "product_name": "Akdeniz Termal Çorap",
        "product_image": "/images/product1.jpg",
        "category": "Çorap",
        "quantity": 2,
        "total_price": 420.0,
        "date": "2026-05-10",
        "status": "kargoda",
        "tracking_number": "YT7845123690",
        "carrier": "YURTİÇİ KARGO",
    },
    {
        "id": "A-240502",
        "customer_id": "C-002",
        "customer_name": "Ayşe Kaya",
        "product_id": "PRD-1002",
        "product_name": "İpek Dokulu Şal — Gece Laciverti",
        "product_image": "/images/product2.jpg",
        "category": "Şal",
        "quantity": 1,
        "total_price": 890.0,
        "date": "2026-05-09",
        "status": "siparis_alindi",
        "tracking_number": "YT7845123691",
        "carrier": "YURTİÇİ KARGO",
    },
    {
        "id": "A-240503",
        "customer_id": "C-003",
        "customer_name": "Zeynep Demir",
        "product_id": "PRD-1003",
        "product_name": "Minimal Altın Küpe Seti",
        "product_image": "/images/product3.jpg",
        "category": "Takı",
        "quantity": 1,
        "total_price": 650.0,
        "date": "2026-05-08",
        "status": "teslim_edildi",
        "tracking_number": "YT7845123692",
        "carrier": "YURTİÇİ KARGO",
    },
    {
        "id": "A-240504",
        "customer_id": "C-004",
        "customer_name": "Merve Arslan",
        "product_id": "PRD-1004",
        "product_name": "El Örgüsü Yün Çorap",
        "product_image": "/images/product4.jpg",
        "category": "Çorap",
        "quantity": 4,
        "total_price": 560.0,
        "date": "2026-05-07",
        "status": "kargoda",
        "tracking_number": "YT7845123693",
        "carrier": "YURTİÇİ KARGO",
        "is_delayed": True,
        "delay_hours": 48,
    },
    {
        "id": "A-240505",
        "customer_id": "C-005",
        "customer_name": "Selin Öztürk",
        "product_id": "PRD-1005",
        "product_name": "Keten Omuz Çantası",
        "product_image": "/images/product5.jpg",
        "category": "Çanta",
        "quantity": 1,
        "total_price": 1250.0,
        "date": "2026-05-06",
        "status": "siparis_alindi",
        "tracking_number": "YT7845123694",
        "carrier": "YURTİÇİ KARGO",
        "is_delayed": True,
        "delay_hours": 32,
    },
    {
        "id": "A-240506",
        "customer_id": "C-006",
        "customer_name": "Burcu Şahin",
        "product_id": "PRD-1006",
        "product_name": "Bohem Püsküllü Şal",
        "product_image": "/images/product6.jpg",
        "category": "Şal",
        "quantity": 2,
        "total_price": 980.0,
        "date": "2026-05-05",
        "status": "teslim_edildi",
        "tracking_number": "YT7845123695",
        "carrier": "YURTİÇİ KARGO",
    },
    {
        "id": "A-240507",
        "customer_id": "C-007",
        "customer_name": "Deniz Aydın",
        "product_id": "PRD-1007",
        "product_name": "Gümüş Yıldız Kolye",
        "product_image": "/images/product7.jpg",
        "category": "Takı",
        "quantity": 1,
        "total_price": 480.0,
        "date": "2026-05-04",
        "status": "kargoda",
        "tracking_number": "YT7845123696",
        "carrier": "YURTİÇİ KARGO",
    },
    {
        "id": "A-240508",
        "customer_id": "C-008",
        "customer_name": "Ceren Polat",
        "product_id": "PRD-1008",
        "product_name": "Pamuklu Sneaker Çorabı (3'lü)",
        "product_image": "/images/product8.jpg",
        "category": "Çorap",
        "quantity": 3,
        "total_price": 360.0,
        "date": "2026-05-03",
        "status": "siparis_alindi",
        "tracking_number": "YT7845123697",
        "carrier": "YURTİÇİ KARGO",
    },
    {
        "id": "A-240509",
        "customer_id": "C-009",
        "customer_name": "Gizem Koç",
        "product_id": "PRD-1001",
        "product_name": "Akdeniz Termal Çorap",
        "product_image": "/images/product1.jpg",
        "category": "Çorap",
        "quantity": 2,
        "total_price": 420.0,
        "date": "2026-05-02",
        "status": "teslim_edildi",
        "tracking_number": "YT7845123698",
        "carrier": "YURTİÇİ KARGO",
    },
    {
        "id": "A-240510",
        "customer_id": "C-010",
        "customer_name": "İrem Çelik",
        "product_id": "PRD-1005",
        "product_name": "Keten Omuz Çantası",
        "product_image": "/images/product5.jpg",
        "category": "Çanta",
        "quantity": 1,
        "total_price": 1250.0,
        "date": "2026-05-01",
        "status": "kargoda",
        "tracking_number": "YT7845123699",
        "carrier": "YURTİÇİ KARGO",
    },
]

products = [
    {
        "id": "PRD-1001",
        "name": "Akdeniz Termal Çorap",
        "category": "Çorap",
        "price": 210.0,
        "stock": 156,
        "description": "Doğal termal iplikten üretilmiş, nefes alan, kışlık çorap.",
        "image_url": "/images/product1.jpg",
        "monthly_sales": [30, 29, 32, 35, 40, 46],
    },
    {
        "id": "PRD-1002",
        "name": "İpek Dokulu Şal — Gece Laciverti",
        "category": "Şal",
        "price": 890.0,
        "stock": 8,
        "description": "İpek karışımlı, özel boya, el işçiliği.",
        "image_url": "/images/product2.jpg",
        "monthly_sales": [12, 10, 14, 11, 9, 8],
        "low_stock_alert": True,
    },
    {
        "id": "PRD-1003",
        "name": "Minimal Altın Küpe Seti",
        "category": "Takı",
        "price": 650.0,
        "stock": 42,
        "description": "14 ayar altın kaplama, hipoalerjenik.",
        "image_url": "/images/product3.jpg",
        "monthly_sales": [18, 22, 25, 30, 28, 35],
    },
    {
        "id": "PRD-1004",
        "name": "El Örgüsü Yün Çorap",
        "category": "Çorap",
        "price": 140.0,
        "stock": 5,
        "description": "El yapımı, %100 yün, her çift farklı desen.",
        "image_url": "/images/product4.jpg",
        "monthly_sales": [20, 18, 15, 12, 10, 8],
        "low_stock_alert": True,
    },
    {
        "id": "PRD-1005",
        "name": "Keten Omuz Çantası",
        "category": "Çanta",
        "price": 1250.0,
        "stock": 22,
        "description": "Organik keten, el dikişi, ayarlanabilir askı.",
        "image_url": "/images/product5.jpg",
        "monthly_sales": [8, 9, 11, 13, 15, 18],
    },
    {
        "id": "PRD-1006",
        "name": "Bohem Püsküllü Şal",
        "category": "Şal",
        "price": 490.0,
        "stock": 33,
        "description": "Viskon-pamuk karışımı, püsküllü kenar.",
        "image_url": "/images/product6.jpg",
        "monthly_sales": [15, 14, 16, 18, 17, 20],
    },
    {
        "id": "PRD-1007",
        "name": "Gümüş Yıldız Kolye",
        "category": "Takı",
        "price": 480.0,
        "stock": 67,
        "description": "925 ayar gümüş, yıldız kolye ucu.",
        "image_url": "/images/product7.jpg",
        "monthly_sales": [22, 25, 28, 30, 33, 38],
    },
    {
        "id": "PRD-1008",
        "name": "Pamuklu Sneaker Çorabı (3'lü)",
        "category": "Çorap",
        "price": 120.0,
        "stock": 120,
        "description": "3'lü set, %80 pamuk, antibakteriyel.",
        "image_url": "/images/product8.jpg",
        "monthly_sales": [40, 42, 45, 48, 50, 55],
    },
]

customers = [
    {"id": "C-001", "name": "Elif Yılmaz", "email": "elif@example.com", "phone": "+90 532 111 1001", "total_orders": 4, "last_order": "2026-05-10"},
    {"id": "C-002", "name": "Ayşe Kaya", "email": "ayse@example.com", "phone": "+90 532 111 1002", "total_orders": 2, "last_order": "2026-05-09"},
    {"id": "C-003", "name": "Zeynep Demir", "email": "zeynep@example.com", "phone": "+90 532 111 1003", "total_orders": 6, "last_order": "2026-05-08"},
    {"id": "C-004", "name": "Merve Arslan", "email": "merve@example.com", "phone": "+90 532 111 1004", "total_orders": 3, "last_order": "2026-05-07"},
    {"id": "C-005", "name": "Selin Öztürk", "email": "selin@example.com", "phone": "+90 532 111 1005", "total_orders": 1, "last_order": "2026-05-06"},
    {"id": "C-006", "name": "Burcu Şahin", "email": "burcu@example.com", "phone": "+90 532 111 1006", "total_orders": 5, "last_order": "2026-05-05"},
    {"id": "C-007", "name": "Deniz Aydın", "email": "deniz@example.com", "phone": "+90 532 111 1007", "total_orders": 2, "last_order": "2026-05-04"},
    {"id": "C-008", "name": "Ceren Polat", "email": "ceren@example.com", "phone": "+90 532 111 1008", "total_orders": 1, "last_order": "2026-05-03"},
    {"id": "C-009", "name": "Gizem Koç", "email": "gizem@example.com", "phone": "+90 532 111 1009", "total_orders": 3, "last_order": "2026-05-02"},
    {"id": "C-010", "name": "İrem Çelik", "email": "irem@example.com", "phone": "+90 532 111 1010", "total_orders": 2, "last_order": "2026-05-01"},
]

shipments = [
    {
        "id": "SHP-001",
        "order_id": "A-240501",
        "customer_id": "C-001",
        "tracking_number": "YT7845123690",
        "carrier": "YURTİÇİ KARGO",
        "status": "dagitimda",
        "steps": ["hazirlaniyor", "kargoya_verildi", "dagitimda"],
        "is_delayed": False,
        "delay_hours": 0,
        "last_update": "2026-05-12T09:00:00",
    },
    {
        "id": "SHP-002",
        "order_id": "A-240502",
        "customer_id": "C-002",
        "tracking_number": "YT7845123691",
        "carrier": "YURTİÇİ KARGO",
        "status": "hazirlaniyor",
        "steps": ["hazirlaniyor"],
        "is_delayed": False,
        "delay_hours": 0,
        "last_update": "2026-05-12T08:00:00",
    },
    {
        "id": "SHP-003",
        "order_id": "A-240503",
        "customer_id": "C-003",
        "tracking_number": "YT7845123692",
        "carrier": "YURTİÇİ KARGO",
        "status": "teslim_edildi",
        "steps": ["hazirlaniyor", "kargoya_verildi", "dagitimda", "teslim_edildi"],
        "is_delayed": False,
        "delay_hours": 0,
        "last_update": "2026-05-11T14:00:00",
    },
    {
        "id": "SHP-004",
        "order_id": "A-240504",
        "customer_id": "C-004",
        "tracking_number": "YT7845123693",
        "carrier": "YURTİÇİ KARGO",
        "status": "kargoya_verildi",
        "steps": ["hazirlaniyor", "kargoya_verildi"],
        "is_delayed": True,
        "delay_hours": 48,
        "last_update": "2026-05-10T10:00:00",
    },
    {
        "id": "SHP-005",
        "order_id": "A-240505",
        "customer_id": "C-005",
        "tracking_number": "YT7845123694",
        "carrier": "YURTİÇİ KARGO",
        "status": "hazirlaniyor",
        "steps": ["hazirlaniyor"],
        "is_delayed": True,
        "delay_hours": 32,
        "last_update": "2026-05-10T08:00:00",
    },
]